/**
 * ============================================================================
 *  The stream contract — the entire read-side event surface.
 * ============================================================================
 *
 *  Sibling to mutations.ts, and it exists for exactly the same reason: the
 *  client and the server must not be able to drift. mutations.ts made that
 *  true for writes from day one. This file is the correction for the fact that
 *  it was never true for events.
 *
 *  The failure it prevents: the live broadcast used to send a per-BATCH summary
 *  with camelCase keys, while catch-up sent per-MUTATION database rows with
 *  snake_case keys and `seq` as a string. Two shapes, two granularities, two
 *  spellings of the sender id — so the client needed two apply paths, and its
 *  echo-skip check silently matched neither. On every reconnect it re-applied
 *  its own writes.
 *
 *  Three rules keep that from coming back:
 *
 *  1. ONE EVENT PER LOG ROW. Never per batch. A batch of five mutations
 *     produces five events. Live and replay differ only in the `replay` flag
 *     and in when they arrive — never in shape.
 *
 *  2. EVERY EVENT CARRIES ITS OWN `seq`. This is what lets a client drop
 *     anything it has already applied, independent of the sender check. Belt
 *     and braces: if the echo check ever breaks again, dedup by seq still
 *     saves us.
 *
 *  3. THE SERVER NEVER GOES QUIET ON A GAP. If a client is too far behind to
 *     replay, it is told so explicitly (`resync`) rather than handed a
 *     truncated prefix and left to believe it is caught up.
 *
 *  Serialised through here on the way out, parsed through here on the way in.
 *  A shape mismatch becomes a loud test failure rather than a duplicated card.
 */

import { z } from 'zod';
import { Mutation } from './mutations.js';

const uuid = z.guid();

/**
 * One applied mutation from the log.
 *
 * Keys are camelCase to match mutations.ts — the client reads `event.clientId`
 * and compares it to the `clientId` it sent in MutationRequest, with no
 * case-juggling in between. The database columns stay snake_case; converting at
 * the boundary is the server's job, not the client's.
 */
const MutationEvent = z.object({
  kind: z.literal('mutation'),

  /** Monotonic log position. A NUMBER — `bigserial` arrives from pg as a
   *  string, and it is coerced once, here, rather than in every consumer. */
  seq: z.number().int().positive(),

  /** The mutation's idempotency key, as generated by the original client. */
  id: uuid,

  /** Who wrote it. Skip the event if this is you — you already applied it
   *  optimistically. Dedup by `seq` covers you if this check ever fails. */
  clientId: uuid,

  /** Duplicated from `mutation.type` so a consumer can route without first
   *  narrowing the union. Always equal to `mutation.type`. */
  type: z.string(),

  /** The mutation itself — the SAME object the writer sent, validated against
   *  the same schema. The client gets a discriminated union it can switch on,
   *  not an opaque payload. */
  mutation: Mutation,

  appliedAt: z.string(),

  /** True when this arrived as catch-up rather than live. Purely informational
   *  — it must NOT change how the event is applied. Always present, so no
   *  consumer has to test for undefined. */
  replay: z.boolean(),
});

/**
 * "Your watermark is unusable; start over."
 *
 * Two reasons, both of which used to end in silent divergence:
 *
 * `too-far-behind` — emitted instead of a truncated catch-up. The old behaviour
 * capped replay at 1000 rows and said nothing, so a client further behind than
 * that set its watermark from the last row it happened to receive, went live, and
 * skipped the gap forever.
 *
 * `ahead-of-head` — the client's watermark is PAST the end of the log. `seq > $1`
 * then matches nothing, so the server sent zero events, held the connection open,
 * and the client sat there believing it was current. This is not exotic: restoring
 * from a dump moves the log head BACKWARDS, so every connected client is instantly
 * ahead of it. Pruning the log does the same. A client in this state has local
 * state describing a future that no longer exists and can never catch up, because
 * there is nothing left to send it.
 *
 * The client should: discard local state, refetch (`/api/schema`,
 * `/api/canvases/:id/scene`), and take its new watermark from the **`seq` the
 * snapshot itself reports** (see Reads), not from `head` here. Those reads are
 * consistent snapshots that report their own log position, so there is no window
 * to replay and nothing to double-apply. `head` is advisory: it tells you how far
 * off you were, which is worth logging.
 */
const ResyncEvent = z.object({
  kind: z.literal('resync'),
  reason: z.enum(['too-far-behind', 'ahead-of-head']),
  /** The log head at the moment the server gave up. */
  head: z.number().int().nonnegative(),
  /** What the client asked for, for diagnostics. */
  since: z.number().int().nonnegative(),
});

export const StreamEvent = z.discriminatedUnion('kind', [MutationEvent, ResyncEvent]);

export type StreamEvent = z.infer<typeof StreamEvent>;
export type MutationEvent = z.infer<typeof MutationEvent>;
export type ResyncEvent = z.infer<typeof ResyncEvent>;

/* ────────────────────────────────────────────────────────────────────────────
 *  Row → event
 *
 *  The one place snake_case becomes camelCase and bigserial becomes a number.
 *  Both the live broadcast and the catch-up loop go through it, which is the
 *  mechanical reason the two can no longer diverge.
 * ──────────────────────────────────────────────────────────────────────────*/

export interface MutationLogRow {
  seq: string | number;
  id: string;
  client_id: string;
  type: string;
  payload: unknown;
  applied_at: Date | string;
}

export function toMutationEvent(row: MutationLogRow, replay: boolean): MutationEvent {
  return MutationEvent.parse({
    kind: 'mutation',
    seq: Number(row.seq),
    id: row.id,
    clientId: row.client_id,
    type: row.type,
    mutation: row.payload,
    appliedAt:
      row.applied_at instanceof Date ? row.applied_at.toISOString() : String(row.applied_at),
    replay,
  });
}

/**
 * Snapshot reads report the log position they were taken at, so a client can
 * set its watermark from the same round trip that gave it the data. Without
 * this there is always a gap or an overlap between "refetch" and "resume".
 */
export const SnapshotMeta = z.object({ seq: z.number().int().nonnegative() });
